In [5]:
import numpy as np
a=np.array([1,2,3.1])

In [6]:
a

array([1. , 2. , 3.1])

In [39]:
b=np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
b[0][0]

1

## Array From Numerical Ranges

### numpy.arange

In [9]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(1,20,2,float)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [25]:
np.arange(10,20,5)

array([10, 15])

### numpy.linspace

In [23]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

### numpy.logspace

In [24]:
import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0,  10) 
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [25]:
a = np.logspace(1.0, 2.0,  10,base=2) 
print (a)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]


In [59]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [36]:
np.random.random((2,3))

array([[0.15576695, 0.82629562, 0.74339138],
       [0.9746606 , 0.73348373, 0.40957206]])

In [38]:
b.shape

(2, 4)

In [41]:
b.size

8

In [43]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [44]:
b.shape=(4,2)

In [45]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
c=np.arange(25)

In [54]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
a.dtype

dtype('int32')

In [60]:
np.sum([1,2,3])

6

In [29]:
np.sum([[1,2],[3,4],[5,6]])

21

In [63]:
np.sum([[1,2],[3,4]],axis=0)

array([4, 6])

In [65]:
np.sum([[1,2],[3,4]],axis=1)

array([3, 7])

In [78]:
np.subtract(1,2)

-1

In [79]:
np.subtract([1,3],[2,4])

array([-1, -1])

In [91]:
a=[1,2]
b=[3,2]

c=[1,2]

In [92]:
np.equal(a,b)



array([False,  True])

In [93]:
np.equal(a,b)

array([False,  True])

In [95]:
np.array_equal(a,c)

True

In [96]:
a=['m','b','c','e']

In [97]:
a

['m', 'b', 'c', 'e']

In [98]:
a[1:3]

['b', 'c']

In [113]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(a)

In [114]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
a[0]

array([1, 2, 3])

In [116]:
a[:1,1:]

array([[2, 3]])

In [119]:
a[2:,1:]

array([[8, 9]])

In [31]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [33]:
c=np.concatenate((a,b))

In [34]:
c

array([1, 2, 3, 4, 5, 6])

In [129]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
import sys

In [136]:
#list
l=range(1000)
print("size of list l is",sys.getsizeof(2)*len(l))

size of list l is 28000


In [132]:
a=np.arange(1000)
print("size of list l is",a.size*a.itemsize)

size of list l is 4000


In [138]:
sys.getsizeof(2)

28

In [134]:
print(l)

range(0, 1000)


In [35]:
a=np.arange(0,60,5)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [36]:
a.reshape([3,4])

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

# Iterations

In [64]:
a=np.arange(0,60,5)
a=a.reshape(3,4)

for x in np.nditer(a):
 print(x,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 

### Order of Iterations

In [67]:
# order='C' ...ROW WISE PRINTING
print("original array",a,sep="\n")
for x in np.nditer(a,order='C'):
    
 print(x,end=" ")

original array
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [66]:
#order='F'........COLUMN WISE PRINTING
print("original array",a,sep="\n")
for x in np.nditer(a,order='F'):
 print(x,end=' ')

original array
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

# Modifying Array Values


In [77]:
print("original array",a,sep="\n")
for x in np.nditer(a,order='C',op_flags=['readwrite']):
    x[...]=2*x

print("modified array",a,sep="\n")

for x in np.nditer(a):
    print(x,end=" ")

original array
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
modified array
[[  0  20  40  60]
 [ 80 100 120 140]
 [160 180 200 220]]
0 20 40 60 80 100 120 140 160 180 200 220 

## External Loop


In [81]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('Original array is:')
print(a)
print ('\n')  

print ('Modified array is:')
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


# Trignometric Functions

In [89]:
a = np.array([0,30,45,60,90]) 
b=np.sin(a*np.pi/180)
b

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [90]:
inv=np.arcsin(b)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [91]:
np.degrees(inv)

array([ 0., 30., 45., 60., 90.])

# Rounding

In [95]:
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:',a,sep='\n') 


print ('After rounding:') 
print (np.around(a) )
print (np.around(a, decimals = 1)) 
print (np.around(a, decimals = -1))

Original array:
[  1.      5.55  123.      0.567  25.532]
After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [97]:
a=np.arange(5)

In [99]:
np.power(a,a)

array([  1,   1,   4,  27, 256], dtype=int32)

In [100]:
np.abs(a)

array([0, 1, 2, 3, 4])

In [101]:
np.mod(a,2)

array([0, 1, 0, 1, 0], dtype=int32)

In [104]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 
np.real(a)

array([-0.,  0., 11.,  1.])

In [105]:
np.imag(a)

array([-5.6,  0.2,  0. ,  1. ])

In [106]:
np.conj(a)

array([-0.+5.6j,  0.-0.2j, 11.-0.j ,  1.-1.j ])

In [107]:
np.angle(a)

array([-1.57079633,  1.57079633,  0.        ,  0.78539816])

In [110]:
np.angle(a,deg=True)

array([-90.,  90.,   0.,  45.])

# MIN AND MAX

In [113]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:') 
print (a)

print ('\n' ) 

print ('Applying amin() function axis=1:') 
print(np.amin(a,1) ) 
print ('\n')  

print( 'Applying amin() function again: axis=0') 
print (np.amin(a,0) )
print ('\n')  

print ('Applying amax() function: default' )
print (np.amax(a) )
print ('\n' ) 

print ('Applying amax() function again: axis=0') 
print( np.amax(a, axis = 0))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function axis=1:
[3 3 2]


Applying amin() function again: axis=0
[2 4 3]


Applying amax() function: default
9


Applying amax() function again: axis=0
[8 7 9]


In [114]:
np.mean(a)

5.0

In [115]:
np.mean(a,axis=0)

array([4.33333333, 5.        , 5.66666667])

In [116]:
np.mean(a,axis=1)

array([5., 5., 5.])

In [118]:
np.median(a)

4.0

In [119]:
np.median(a,axis=0)

array([3., 4., 5.])

In [120]:
np.median(a,axis=1)

array([5., 4., 4.])

In [121]:
np.std(a)

2.309401076758503

In [122]:
np.std(a,axis=1)

array([1.63299316, 2.1602469 , 2.94392029])

In [123]:
np.std(a,axis=0)

array([2.62466929, 1.41421356, 2.49443826])

In [124]:
np.var(a)

5.333333333333333

In [125]:
np.var(a,axis=1)

array([2.66666667, 4.66666667, 8.66666667])

In [126]:
np.var(a,axis=0)

array([6.88888889, 2.        , 6.22222222])