In [1]:
from sklearn import datasets

In [2]:
iris=datasets.load_iris()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
import pandas as pd

In [10]:
data= pd.DataFrame({'sepal length':iris.data[:,0],
                   'sepal width':iris.data[:,1],
                   'petal length':iris.data[:,2],
                   'petal width':iris.data[:,3],
                   'species':iris.target})

In [11]:
data.head()

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [37]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]


In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=31)

In [39]:
x_train.shape

(105, 4)

In [40]:
x_test.shape

(45, 4)

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
clf=RandomForestClassifier(n_estimators=110)

In [43]:
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=110,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [44]:
y_pred=clf.predict(x_test)

In [45]:
from sklearn import metrics

In [46]:
metrics.accuracy_score(y_pred,y_test)

0.9777777777777777

In [33]:
clf.predict([[3,4,5,1]])

array([2])

In [34]:
features=clf.feature_importances_

In [35]:
print(features)
#sl=8% sw=2% pl=43% pw=46%

[0.08275572 0.01997351 0.43166415 0.46560662]


In [36]:
data.drop('sepal width',axis=1)

sepal length  petal length  petal width  species
0             5.1           1.4          0.2        0
1             4.9           1.4          0.2        0
2             4.7           1.3          0.2        0
3             4.6           1.5          0.2        0
4             5.0           1.4          0.2        0
..            ...           ...          ...      ...
145           6.7           5.2          2.3        2
146           6.3           5.0          1.9        2
147           6.5           5.2          2.0        2
148           6.2           5.4          2.3        2
149           5.9           5.1          1.8        2

[150 rows x 4 columns]

In [47]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=31)

In [48]:
clf=RandomForestClassifier(n_estimators=110)
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=110,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [49]:
y_pred=clf.predict(x_test)
metrics.accuracy_score(y_pred,y_test)

0.9777777777777777

In [ ]:

https://drive.google.com/open?id=1xbZaXtofOnwUgPcHC_-9fQgli3P3Pmti
