In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics


In [1]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy'] 
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [2]:
from sklearn.preprocessing import LabelEncoder

le =LabelEncoder()

weather=le.fit_transform(weather)
print (weather)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [46]:
temp=le.fit_transform(temp)
print(temp)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [47]:
play=le.fit_transform(play)
print(play)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [48]:
data=pd.DataFrame({'weather':weather,'temp':temp,'play':play})
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [49]:
data

weather  temp  play
0         2     1     0
1         2     1     0
2         0     1     1
3         1     2     1
4         1     0     1
5         1     0     0
6         0     0     1
7         2     2     0
8         2     0     1
9         1     2     1
10        2     2     1
11        0     2     1
12        0     1     1
13        1     2     0

In [50]:
x.shape

(14, 2)

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [52]:
x_train.shape

(9, 2)

In [53]:
y_train.shape

(9,)

### using Logistic Regression

In [62]:
logistic_model=LogisticRegression()

In [63]:
logistic_model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [65]:
y_pred=logistic_model.predict(x_test)
print(y_pred)

[1 1 1 1 1]


In [67]:
metrics.accuracy_score(y_test,y_pred)

0.6

### USING NAVIE_BAYEAS

In [68]:
Navies_model=GaussianNB()

In [69]:
Navies_model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [70]:
y_pred=Navies_model.predict(x_test)

In [73]:
metrics.accuracy_score(y_test,y_pred)


0.6

In [72]:
print(y_pred)

[1 1 1 0 0]


In [74]:
y_test

11    1
4     1
5     0
0     0
9     1
Name: play, dtype: int64